name: Flask CI

on:
  push:
    branches: [main, master]  # Setting this action to run on push to main or master branches

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu is a widely used Linux distribution

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Check out the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Specify Python version

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print Debugging Information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Content of Working Directory: $(ls -l)"
          echo "Content of site-packages: $(ls -l venv/lib/python*/site-packages)"

  test:
    needs: build
    runs-on: ubuntu-latest  # Ubuntu is a widely used Linux distribution

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest discover -s tests -p 'test_*'.py






